#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.2f1_c18cef34cbcd"
#define UNITY_VERSION_FULL_NICE "2018.2.2f1 (c18cef34cbcd)"
#define UNITY_VERSION_BLD 12684527
#define UNITY_VERSION_DATE 1532595656
#define UNITY_VERSION_WIN "2018.2.2.12684527"
#define UNITY_VERSION_BRANCH "2018.2/release"
